resolver: nightly-2018-06-10
packages:
- 'reactive-banana-gi-gtk'
- 'example'
extra-deps: [
  'reactive-banana-1.2.0.0',
  'gi-gtk-3.0.23',
  'gi-gdk-3.0.16',
  'gi-gdkpixbuf-2.0.16',
  'gi-gio-2.0.18',
  'gi-pango-1.0.16'
]
pvp-bounds: both
